#include "hyprinputconfig.h"

#include <optional>

#include <QtCore>
#include <qbuffer.h>
#include <qcontainerfwd.h>
#include <qdebug.h>
#include <qlist.h>
#include <qloggingcategory.h>
#include <qobject.h>
#include <qqmllist.h>
#include <qstringview.h>
#include <qtypes.h>

#include "hyprkeyboardlayout.h"
#include "kbdlayouts.h"

namespace ns::hyprland {
Q_DECLARE_LOGGING_CATEGORY(logNSHyprland) // from hyprland.cpp

using STRING_PAIR = QPair<QString, QString>;

HyprInputConfig::HyprInputConfig(QObject *parent) : QObject(parent) {}

QQmlListProperty<HyprKeyboardLayout> HyprInputConfig::layouts() {
  return QQmlListProperty<HyprKeyboardLayout>(
      this,
      &m_layouts,
      [](QQmlListProperty<HyprKeyboardLayout> *property) {
        auto *list = static_cast<QList<HyprKeyboardLayout *> *>(property->data);
        return list->count();
      },
      [](QQmlListProperty<HyprKeyboardLayout> *property, qsizetype index) {
        auto *list = static_cast<QList<HyprKeyboardLayout *> *>(property->data);
        return list->at(index);
      });
}

QList<HyprKeyboardLayout *> HyprInputConfig::layoutList() const {
  return m_layouts;
}

void HyprInputConfig::setLayouts(QStringList &layouts,
                                 QStringList &variants) {
  QList<STRING_PAIR> pairList(layouts.size());
  pairList.reserve(layouts.size());
  variants.resize(layouts.size());
  for (auto i = 0; i < layouts.size(); ++i) {
    pairList.append(
        STRING_PAIR(std::move(layouts.at(i)), std::move(variants.at(i))));
  }
  this->setLayouts(pairList);
}

void HyprInputConfig::setLayouts(const QList<STRING_PAIR> &layouts) {
  auto                        old = m_layouts;
  QList<HyprKeyboardLayout *> newLayouts;
  newLayouts.reserve(layouts.size());

  for (const auto &layout : layouts) {
    auto oldIt = std::ranges::find_if(
        old.begin(), old.end(), [layout](HyprKeyboardLayout *it) {
          return it->layout() == layout.first && it->variant() == layout.second;
        });
    if (oldIt != old.end()) {
      old.erase(oldIt);
      newLayouts.append(*oldIt);
    } else {
      auto l = utils::KeyboardLayouts::instance()->fetchLayoutMetadata(
          layout.first, layout.second);
      if (!l.has_value()) continue;

      auto lmeta   = l.value();
      auto klayout = new HyprKeyboardLayout(std::move(lmeta.name),
                                            std::move(lmeta.variant),
                                            std::move(lmeta.description),
                                            this);
      newLayouts.append(klayout);
    }
  }

  if (newLayouts != m_layouts) {
    m_layouts = newLayouts;
    emit layoutsChanged();
  }

  for (auto &cleanup : old) {
    cleanup->deleteLater();
  }
}

bool HyprInputConfig::saveToConfigFile(QStringView filePath) {
  QStringList layouts, variants;
  layouts.reserve(m_layouts.size());
  variants.reserve(m_layouts.size());

  for (const auto &l : m_layouts) {
    layouts.append(l->layout());
    variants.append(l->variant());
  }

  if (layouts.isEmpty()) {
    layouts.append("us");
  }

  auto writeBuffer = QString("-- WARNING!\n"
                             "-- This file is automatically generated by the "
                             "shell, avoid making any changes.\n\n"
                             "hl.config({\n"
                             "\tinput = {\n"
                             "\t\tkb_layout = \"%0\"\n"
                             "\t\tkb_variant = \"%1\"\n"
                             "\t\tkb_model = \"%2\"\n"
                             "\t\tkb_options = \"%3\"\n"
                             "\t\tkb_rules = \"%4\"\n"
                             "\t}\n})")
                         .arg(layouts.join(","),
                              variants.join(","),
                              m_kbModel,
                              m_kbOptions,
                              m_kbRules);

  QSaveFile file(filePath.toString(), this);
  if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
    qCWarning(logNSHyprland)
        << "Failed to open hyprland input config file for saving.";
    return false;
  }
  QTextStream out(&file);
  out << writeBuffer;

  if (!file.commit()) {
    qCWarning(logNSHyprland) << "Failed committing to hyprland input config "
                                "file. Changes were discarded.";
    return false;
  }

  return true;
}
} // namespace ns::hyprland
